sudo: required
language: java
jdk:
- openjdk8
before_script:
- wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
- unzip gradle-6.5-bin.zip
- export GRADLE_HOME=$PWD/gradle-6.5
- export PATH=$GRADLE_HOME/bin:$PATH
addons:
  sonarcloud:
    organization: api-testing-01
    token: "$SONAR_TOKEN"
script:
- gradle compileJava compileTestJava
- sonar-scanner
- gradle check
- gradle clean runFeatures
notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_8a4b7cf0a4fc_key -iv $encrypted_8a4b7cf0a4fc_iv
  -in config.json.enc -out config.json -d
